# Generated by Django 4.1.1 on 2022-10-25 09:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=40)),
                ('code', models.CharField(max_length=2)),
                ('user', models.ManyToManyField(related_name='languages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
