# Generated by Django 4.1.1 on 2022-11-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0002_alter_deck_language_alter_deck_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='name',
            field=models.CharField(default='other cards', max_length=40),
        ),
    ]
