# Generated by Django 4.1.1 on 2022-11-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0005_alter_deck_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='name',
            field=models.CharField(default='Other cards', max_length=40),
        ),
    ]
